### ISSUE TITLE
Implement Misreporting of Valuation Distributions

### ISSUE THREAD

**Issue by degregat** [mechanism-learning-research/two-player-auctions#4]
We need to implement sampling from manipulated distributions, to simulate agents misreporting Valuation Distributions. 
A sketch:

1. create a copy of misreporter to be used as ValuationMisreporter
2. extend ValuationMisreporter, s.t. individual agents can be set to misreport while all other keep reporting/sampling truthfully
3. use ValuationMisreporter in an outer loop in place of the bid sampler. There are two settings of interest:
- Online attack, interactive, assumes one report per iteration: outer loop gets access to auctions from every iteration of the inner loop and calculates optimal misreport. (this assumes adversarial online learning, where the attacker has full access)

- Offline attack, non-interactive, assumes reporting samples from a manipulated distribution without access to intermediate models: let the inner loop sample from a distribution (e.g. U(0,1) ) and have the ValuationMisreporter sample from a family of others (e.g. U(0.3, 1.3), U(0.5, 1.5), N(0,1)), set at the beginning.

BidSampler is still used during regret computation in both settings, since it instantiates the actual Valuation Distributions of agents misreporting their Valuation Distributions.

4. verify that baselines get reproduced when all valuations are being reported truthfully. approximate reproduction is fine if the changes in deterministic randomness from refactoring the sampler are too hard to control.

**Comment by undefdev** [comment]
Offline attack is implemented in 1ce21bd and reproduces baseline with truthful reporting.
