### ISSUE TITLE
Add differential privacy to report ingestion

### ISSUE THREAD

**Issue by degregat** [mechanism-learning-research/two-player-auctions#5]
We want to introduce controlled noise via DP methods into the reporting process, to test how much robustness we can gain for the downstream model learning.

A sketch:
1. Add noise once at the boundary where samples from valuation_reporter are ingested. 
Use https://github.com/IBM/discrete-gaussian-differential-privacy (or https://github.com/google-deepmind/jax_privacy if it provides an interface to perform non-iterated noising). We might want to do [input perturbation](https://arxiv.org/pdf/2002.08570.pdf) instead of DP-SGD, if we want to train for more than one iteration per sample.
2. Verify non-DP codepath still reproduces baseline with truthful valuation reports and no DP.
3. Check if DP codepath reproduces baseline (approximately). This is nice to have but not critical.

4. Run baseline settings with a family of DP parameters.

**Comment by undefdev** [comment]
5. Update readme to explain usage of added features

**Comment by undefdev** [comment]
closed in 09a6705
